# Site settings
title: FATTAL-FairFight
description: A blog about software development and other things
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: FATTAL-FairFight
user_description: A man who is passionate about software development and other things
user_title: DevSecOps Engineer
email: fattal_fairfight@hotmail.com
twitter_username: .
github_username:  FATTAL-FairFight
gplus_username:  .

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
